version: '3'

services:
  app_vehicles:
    build:
      context: ./front/
      target: dev
    container_name: app_vehicles
    volumes:     
      - ./front:/app
      - nodemodulesapp:/app/node_modules
    command: yarn dev
    ports:
      - '3000:3000'
    networks:
      - app-network
    links:
      - api_vehicles
    depends_on:
      - api_vehicles

  api_vehicles:
    container_name: api_vehicles
    build:
      context: ./server/
      target: dev
    volumes:
      - ./server:/app
      - nodemodulesapi:/app/node_modules
    command: yarn dev
    ports:
      - "3333:3333"
    environment: 
      MONGO_URL: mongodb
    networks:
      - app-network
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:     
      - dbdata:/data/db
    networks:
      - app-network  

networks:
  app-network:

volumes:
  dbdata:
  nodemodulesapp:
  nodemodulesapi: